AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Servico CloudFormation para a aplicação All In Your Hands

Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  LambdaSpringBootFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ricardombertani.projetos.allinyourhands.microservico.LambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/microservico-0.0.1-SNAPSHOT.jar
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  AiyhSpringBootApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage'
    Export:
      Name: AiyhAPIs